### ISSUE TITLE
Projection not stopped when stop message is omitted

### ISSUE THREAD

**Issue by octonato** [akka/akka-projection#586] opened 2021-09-01 20:14 UTC
I got this reported by @eloots. 

The sharded daemon won't properly stop a projection if we don't explicitly pass `ProjectionBehavior.Stop` message to it. 

This is quite odd because it seems to be a problem only when the underlying behavior is `ProjectionBehavior`. I suspect this is a bug in Akka and it's only trigger in some edge cases, but since I can only reproduce it with projections, I'm reporting here for now. 

I will publish a reproducer soon.

**Comment by octonato** [comment] 2021-09-01 20:16
Here is the reproducer
https://github.com/octonato/reproducer-for-projection-586

**Comment by johanandren** [comment] 2021-10-01 15:32
The sharded daemon process should kill the actor if you do not specify a stop message, but maybe the actor does not clean up stuff if abruptly terminated?

Should be fixed, but the docs should also include stop message.

**Comment by johanandren** [comment] 2021-10-01 15:41
Sorry, the docs looks right already, not sure why I thought they werent: https://doc.akka.io/docs/akka-projection/current/running.html#initializing-the-sharded-daemon

**Comment by eloots** [comment] 2021-10-01 15:55
The issue is that there are 3 polymorphic versions of ShardedDaemonProcess.init and one of them doesn’t have a stopMessage parameter (see: https://doc.akka.io/api/akka/current/akka/cluster/sharding/typed/scaladsl/ShardedDaemonProcess.html <https://doc.akka.io/api/akka/current/akka/cluster/sharding/typed/scaladsl/ShardedDaemonProcess.html>).

It’s this specific variant that is at the base of this issue.

**Comment by eloots** [comment] 2021-10-01 16:17
In that case, I think it might be a good idea to point that out in the documentation (or alternatively, deprecate the 3rd form)

**Comment by patriknw** [comment] 2021-10-01 17:53
I think we can conclude that this is a bug, and there exists a workaround. We haven't got the cycles to fix it (yet). Contributions are welcome.

**Closed** 2022-05-11 08:36 UTC
Labels: bug
