### ISSUE TITLE
fail: atLeastOnceShouldRestartFromPreviousOffset

### ISSUE THREAD

**Issue by octonato** [akka/akka-projection#648] opened 2022-03-10 21:11 UTC
Similar to issues fixed in #647, but on JDBC. 

```scala
[info] - atLeastOnceShouldRestartFromPreviousOffset *** FAILED ***
[info]   org.junit.ComparisonFailure: expected:<abc|def|[ghi|]> but was:<abc|def|[]>
[info]   at org.junit.Assert.assertEquals(Assert.java:117)
[info]   at org.junit.Assert.assertEquals(Assert.java:146)
[info]   at akka.projection.jdbc.JdbcProjectionTest.lambda$atLeastOnceShouldRestartFromPreviousOffset$2e5cadc3$1(JdbcProjectionTest.java:342)
[info]   at akka.projection.testkit.javadsl.ProjectionTestKit.$anonfun$runWithTestSink$1(ProjectionTestKit.scala:98)
[info]   at akka.projection.testkit.javadsl.ProjectionTestKit.$anonfun$runWithTestSink$1$adapted(ProjectionTestKit.scala:98)
[info]   at akka.projection.testkit.scaladsl.ProjectionTestKit.runWithTestSink(ProjectionTestKit.scala:126)
[info]   at akka.projection.testkit.javadsl.ProjectionTestKit.runWithTestSink(ProjectionTestKit.scala:98)
[info]   at akka.projection.jdbc.JdbcProjectionTest.atLeastOnceShouldRestartFromPreviousOffset(JdbcProjectionTest.java:331)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   at java.lang.reflect.Method.invoke(Method.java:498)
```

_Originally posted by @octonato in https://github.com/akka/akka-projection/issues/647#issuecomment-1064508159_

**Comment by pvlugter** [comment] 2023-01-24 23:17
https://github.com/akka/akka-projection/actions/runs/3999762666/jobs/6864057802#step:6:418

**Comment by pvlugter** [comment] 2023-01-24 23:19
Duplicate of #465

**Closed by pvlugter** 2023-01-24 23:19 UTC
Labels: fail
