### ISSUE TITLE
Failed: R2dbcProjectionSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka-projection#992] opened 2023-09-07 08:27 UTC
https://github.com/akka/akka-projection/actions/runs/6107228135/job/16573823036#step:6:1060

With H2

```
[info] - must pause projection *** FAILED *** (10 seconds, 151 milliseconds)
[info]   The code passed to eventually never returned normally. Attempted 110 times over 10.096459222 seconds. Last failure message: Some(5) was not equal to Some(6). (R2dbcProjectionSpec.scala:1373)
[info]   org.scalatest.exceptions.TestFailedDueToTimeoutException:
[info]   at org.scalatest.enablers.Retrying$$anon$4.tryTryAgain$2(Retrying.scala:219)
[info]   at org.scalatest.enablers.Retrying$$anon$4.retry(Retrying.scala:226)
[info]   at org.scalatest.concurrent.Eventually.eventually(Eventually.scala:415)
[info]   at org.scalatest.concurrent.Eventually.eventually$(Eventually.scala:414)
[info]   at akka.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit.eventually(ScalaTestWithActorTestKit.scala:31)
[info]   at akka.projection.r2dbc.R2dbcProjectionSpec.$anonfun$new$159(R2dbcProjectionSpec.scala:1373)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1240)
[info]   at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture(LogCapturing.scala:70)
[info]   at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture$(LogCapturing.scala:68)
[info]   at akka.projection.r2dbc.R2dbcProjectionSpec.withFixture(R2dbcProjectionSpec.scala:170)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1238)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1250)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1250)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1232)
[info]   at akka.projection.r2dbc.R2dbcProjectionSpec.runTest(R2dbcProjectionSpec.scala:170)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1309)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
[info]   at scala.collection.immutable.List.foreach(List.scala:333)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
[info]   at scala.collection.immutable.List.foreach(List.scala:333)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1309)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1308)
[info]   at akka.projection.r2dbc.R2dbcProjectionSpec.runTests(R2dbcProjectionSpec.scala:170)
```

**Comment by johanandren** [comment] 2023-09-07 11:17
https://github.com/akka/akka-projection/actions/runs/6107511594/job/16574662645?pr=994#step:6:1060

**Comment by johanandren** [comment] 2023-09-07 11:18
Full logs from failed run

[6_Run integration tests with with Scala and Java 1.17.0.txt](https://github.com/akka/akka-projection/files/12548021/6_Run.integration.tests.with.with.Scala.and.Java.1.17.0.txt)

**Comment by johanandren** [comment] 2023-09-07 12:49
https://github.com/akka/akka-projection/actions/runs/6109500942/job/16580652552

**Comment by johanandren** [comment] 2023-09-07 13:33
Last two are probably not the same as the first, but more curious: `Some("e1|e2|e3|e4|e5|e6|e1|e2|e3|e5|e6") was not equal to Some("e1|e2|e3|e4|e5|e6|e1|e2|e3|e4|e5|e6")` note that the e4 event is missed after restarting the projection, 

debug logs show an upsert with e4 present, but then the next upsert is missing it:
```
[2023-09-07 08:51:04,667] [DEBUG] [akka.projection.r2dbc.R2dbcProjectionSpec$TestRepository] [] [] [R2dbcTimestampOffsetProjectionSpec-akka.actor.default-dispatcher-7] - TestRepository.upsert: [ConcatStr(80bfa055-1ee6-4b95-9fdd-72c73a4697c0,e1|e2|e3|e4|e5|e6|e1|e2|e3|e4)]
[2023-09-07 08:51:04,667] [DEBUG] [akka.projection.r2dbc.R2dbcProjectionSpec$TestRepository] [] [] [R2dbcTimestampOffsetProjectionSpec-akka.actor.default-dispatcher-6] - TestRepository.findById: [80bfa055-1ee6-4b95-9fdd-72c73a4697c0]
[2023-09-07 08:51:04,668] [DEBUG] [akka.projection.r2dbc.R2dbcProjectionSpec$TestRepository] [] [] [R2dbcTimestampOffsetProjectionSpec-akka.actor.default-dispatcher-5] - TestRepository.findById: [80bfa055-1ee6-4b95-9fdd-72c73a4697c0]
[2023-09-07 08:51:04,668] [DEBUG] [akka.projection.r2dbc.R2dbcProjectionSpec$TestRepository] [] [] [R2dbcTimestampOffsetProjectionSpec-akka.actor.default-dispatcher-5] - TestRepository.upsert: [ConcatStr(80bfa055-1ee6-4b95-9fdd-72c73a4697c0,e1|e2|e3|e4|e5|e6|e1|e2|e3|e5)]
```

**Comment by pvlugter** [comment] 2023-09-15 04:44
I think I've tracked down the underlying issue now. Added a bunch of debug println to H2 to see what was going on.

It's not an issue with the H2 multi-version store itself. Can see the previous version is correct when skipping an event:

```
MVMap.operate - PUT - key: [12], value: [( /* key:12 */ '6be3cfa9-a706-4b1d-91dd-0b849c6dd394', 'e1|e2|e4') 1/3 ( /* key:12 */ '6be3cfa9-a706-4b1d-91dd-0b849c6dd394', 'e1|e2|e3')]
```

So it's when getting the current value before concatenating, and it sees the previous value instead. There's a cache for the previous result for a query, which is used by default if there's been no modification to the table. The race condition is on the modification check. And needs a few things together to create this issue. The normal pattern is:

- value for the projected row is currently `A`
- modification counter is currently `N`
- query cache has `A` as its last value, tracked at modification counter `N`
- process event - update value from `A` to `A|B` and commit transaction
- modification counter is incremented to `N+1`
- next query sees that the max modification counter `N+1` is higher than `N` and doesn't reuse the cached value
- query fetches and returns updated value `A|B` as expected

But given queries running concurrently to the projection processing, a gap between updating the modification counter and committing to store, and a switch between pooled connections, we can get this pattern instead:

- value for the projected row is currently `A`
- modification counter is currently `N`
- process event - update value from `A` to `A|B` and commit transaction (on connection `1`)
- modification counter is incremented to `N+1`, before the underlying commit to store
- before value `A|B` is stored, there's a concurrent fetch for this row (on connection `2`)
- query returns `A`, but tracked for the updated modification counter of `N+1` **<-- this is the bug**
- value `A|B` is committed to storage
- process next event - but on connection `1` now, where the query cache is incorrect
- fetching the current value before update sees that the last modification counter `N+1` is up-to-date
- uses cached value `A` instead of retrieving the updated value `A|B`
- upsert to `A|C` instead of `A|B|C`

Didn't show up often in tests, because of it being a race with tight timing, the cache per connection, and that the concurrent queries from the testing had retry delays. So looping continuously on concurrent queries made it easier to reproduce.

We can report this to H2. But not sure if there will be a straightforward fix.

As a workaround, the caching can be disabled for now, with `OPTIMIZE_REUSE_RESULTS=FALSE`. Haven't seen any other failures with this result cache disabled.

**Comment by pvlugter** [comment] 2023-09-15 04:53
Tested by setting `OPTIMIZE_REUSE_RESULTS` in `additional-options` for the tests. Always disabling this for now in https://github.com/akka/akka-persistence-r2dbc/pull/456.

**Comment by patriknw** [comment] 2023-09-15 06:48
Wow, great finding. I think it would be good to report an issue to H2. We don't have to work on fixing it or provide more details than the description you wrote above.

**Comment by pvlugter** [comment] 2023-09-15 07:02
A fix in H2 could simply be reversing the order: first commit to the store, then update the modification counters. It could then have the flipped situation in the query cache instead, the latest value with an older modification id, but should only mean that it does another fetch rather than using the previous result. And wouldn't break consistency. Providing nothing else relies on this order.

**Comment by pvlugter** [comment] 2023-09-18 00:48
Reported to H2 here: https://github.com/h2database/h2database/issues/3894

**Closed** 2023-09-18 06:48 UTC
Labels: fail
