### ISSUE TITLE
faile: wrong logger loaded

### ISSUE THREAD

**Issue by renatocaval** [akka/akka-projection#106] opened 2020-05-08 16:11 UTC
Test failure with:

```scala
[info] HandlerRecoveryImplSpec:
[info] akka.projection.internal.HandlerRecoveryImplSpec *** ABORTED *** (2 milliseconds)
SLF4J: A number (3) of logging calls during the initialization phase have been intercepted and are
SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#replay
[info]   java.lang.IllegalArgumentException: Requires Logback logger for [], it was a [org.slf4j.helpers.SubstituteLogger]
[info]   at akka.actor.testkit.typed.internal.LogbackUtil$.getLogbackLogger(LogbackUtil.scala:26)
[info]   at akka.actor.testkit.typed.internal.CapturingAppender$.get(CapturingAppender.scala:21)
[info]   at akka.actor.testkit.typed.scaladsl.LogCapturing.$init$(LogCapturing.scala:36)
[info]   at akka.projection.internal.HandlerRecoveryImplSpec.<init>(HandlerRecoveryImplSpec.scala:43)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```

**Comment by renatocaval** [comment] 2020-05-08 16:12
Happened in #103. Only difference in that module is that I added akka-actor typed

**Comment by renatocaval** [comment] 2020-05-11 15:12
Got another one like this in #112

**Comment by seglo** [comment] 2020-05-13 18:38
This is happening in #130 as well. I can't reproduce it reliably.

**Comment by patriknw** [comment] 2020-05-13 19:28
@ennru has a fix for this in Alpakka and will incorporate it in Akka. Nothing we can/should do here in Projections.

**Comment by patriknw** [comment] 2020-05-14 12:02
Solved in Akka https://github.com/akka/akka/pull/29070
Keeping this issue open until we upgrade.

**Closed** 2020-06-17 07:41 UTC
Labels: fail
